### ISSUE TITLE
После регистрации должно сразу логинить

### ISSUE THREAD

**Issue by sebaks** [pbblg/pbblg#21]

**Comment by maxgu** [comment]
Что-то мне кажется этого нельзя сделать вообще, т.к. если у тебя в другой вкладке открыта :3000 или :8080 - и ты там аноним, авторизационная кука не появится там пока не перегрузишь страницу, и сообщения из сокета ты не получишь, т.к. ты аноним

**Comment by sebaks** [comment]
Сейчас так:
1. регистрируюсь тут  тут http://localhost:8080/register
2. нажимаю играть 
3. попадаю http://localhost:8080/game и вижу You are not logged, please login.

**Comment by sebaks** [comment]
Сессия моя в базе есть и кука у меня тут http://localhost:8080/game есть. Даже есть кука accessToken

**Comment by sebaks** [comment]
А если сделать логин http://localhost:8080/login и нажать играть - то робе.

**Comment by maxgu** [comment]
>  1. регистрируюсь тут тут http://localhost:8080/register
>  2. нажимаю играть
>  3. попадаю http://localhost:8080/game и вижу You are not logged, please login.

да, так должно работать

**Comment by shirokikhyura** [comment]
Я почти сделал только тест надо править сложно немного

**Comment by shirokikhyura** [comment]
Можно баг закрыть проблема решена
